In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("cleaned_NFL_combine_97_to_2018.csv")
df.head()

,year,name,college,position,height_in,weight_lbs,40yards,benchpress,vert_leap_in,broad_jump_in,shuttle,3cone,drafted
0,1997,mike adams,Texas,WR,71.4,184,4.59,NaN,29.5,112.0,4.38,7.51,N
1,1997,winston alderson,Arkansas,OT,76.1,344,5.60,NaN,24.5,92.0,5.25,8.85,N
2,1997,ink aleaga,Washington,ILB,73.0,227,4.87,NaN,31.0,107.0,4.33,7.60,N
3,1997,eric allen,Indiana,FS,72.0,205,4.78,NaN,34.0,116.0,4.22,7.27,N
4,1997,james allen,Oklahoma,RB,70.1,212,NaN,11.0,31.0,NaN,NaN,NaN,N

In [3]:
df.groupby(["position", "drafted"])["40yards"].describe()
# Significance K 4.74-4.96 Y N 4.93-5.17

                  count      mean       std   min     25%    50%     75%   max
position drafted
C        N         77.0  5.275714  0.193822  4.82  5.1700  5.250  5.4000  5.84
         Y         99.0  5.247475  0.148016  4.89  5.1500  5.250  5.3300  5.64
CB       N        174.0  4.564080  0.099664  4.33  4.4900  4.570  4.6300  4.95
         Y        427.0  4.487190  0.084501  4.25  4.4300  4.490  4.5400  4.78
DB       N          1.0  4.620000       NaN  4.62  4.6200  4.620  4.6200  4.62
         Y          3.0  4.466667  0.080829  4.38  4.4300  4.480  4.5100  4.54
DE       N        143.0  4.917483  0.136513  4.53  4.8200  4.920  5.0000  5.27
         Y        365.0  4.819397  0.132162  4.48  4.7300  4.820  4.9000  5.26
DL       N          1.0  4.880000       NaN  4.88  4.8800  4.880  4.8800  4.88
         Y          3.0  4.756667  0.040415  4.72  4.7350  4.750  4.7750  4.80
DT       N        153.0  5.153922  0.169827  4.77  5.0300  5.150  5.2700  5.77
         Y        317.0  5.102681  0.158518  4.68  5.0000  5.090  5.1900  5.71
FB       N         55.0  4.800545  0.150412  4.60  4.6950  4.760  4.8850  5.37
         Y         77.0  4.759870  0.126735  4.48  4.6700  4.750  4.8300  5.03
FS       N         93.0  4.638495  0.106004  4.36  4.5800  4.630  4.7200  4.95
         Y        171.0  4.554152  0.098182  4.31  4.5000  4.560  4.6100  4.84
ILB      N         92.0  4.849783  0.114066  4.65  4.7600  4.840  4.9200  5.19
         Y        181.0  4.733370  0.121638  4.42  4.6500  4.730  4.8200  5.14
K        N          6.0  5.046667  0.103859  4.93  4.9600  5.040  5.1350  5.17
         Y          4.0  4.837500  0.095350  4.74  4.7775  4.825  4.8850  4.96
LB       N          2.0  4.845000  0.091924  4.78  4.8125  4.845  4.8775  4.91
         Y          9.0  4.636667  0.071937  4.46  4.6300  4.650  4.6700  4.70
LS       N          4.0  5.065000  0.167033  4.91  4.9775  5.025  5.1125  5.30
         Y          2.0  5.050000  0.197990  4.91  4.9800  5.050  5.1200  5.19
NT       N          0.0       NaN       NaN   NaN     NaN    NaN     NaN   NaN
OG       N        166.0  5.397289  0.210461  4.95  5.2700  5.400  5.5200  6.12
         Y        244.0  5.274098  0.158370  4.90  5.1600  5.280  5.3900  5.66
OL       N          0.0       NaN       NaN   NaN     NaN    NaN     NaN   NaN
         Y          2.0  5.190000  0.042426  5.16  5.1750  5.190  5.2050  5.22
OLB      N        131.0  4.760534  0.118473  4.50  4.6800  4.760  4.8350  5.03
         Y        315.0  4.669429  0.114145  4.38  4.6000  4.650  4.7400  5.09
OT       N        135.0  5.355333  0.182776  4.81  5.2350  5.360  5.4600  5.94
         Y        331.0  5.256103  0.190318  4.71  5.1400  5.260  5.3700  6.03
P        N         11.0  4.954545  0.136775  4.70  4.9050  4.980  5.0600  5.12
         Y          4.0  4.877500  0.223961  4.64  4.7825  4.845  4.9400  5.18
QB       N        160.0  4.884062  0.175776  4.33  4.7700  4.870  5.0125  5.37
         Y        210.0  4.828429  0.173014  4.33  4.7100  4.835  4.9375  5.37
RB       N        239.0  4.615732  0.116208  4.29  4.5400  4.620  4.6900  4.98
         Y        316.0  4.536108  0.101839  4.27  4.4675  4.530  4.6000  4.84
SS       N         85.0  4.641412  0.124395  4.36  4.5600  4.630  4.6900  5.02
         Y        138.0  4.554710  0.080547  4.34  4.5000  4.560  4.6000  4.80
TE       N        130.0  4.861385  0.139205  4.46  4.7800  4.880  4.9700  5.16
         Y        218.0  4.764954  0.142955  4.38  4.6800  4.780  4.8575  5.26
WR       N        286.0  4.584406  0.098587  4.31  4.5100  4.580  4.6500  4.85
         Y        503.0  4.495586  0.097969  4.21  4.4300  4.500  4.5600  4.76

In [4]:
df.groupby(["position", "drafted"])["benchpress"].describe()
# OL 26 - 34 Y N 22 - 23

                  count       mean       std   min    25%   50%    75%   max
position drafted
C        N         73.0  25.315068  5.275406  14.0  23.00  25.0  28.00  38.0
         Y         95.0  26.484211  4.837494  17.0  23.00  27.0  29.00  41.0
CB       N        143.0  13.272727  4.308821   2.0  10.00  14.0  16.00  24.0
         Y        364.0  14.876374  4.215751   2.0  12.00  15.0  17.00  32.0
DB       N          1.0  18.000000       NaN  18.0  18.00  18.0  18.00  18.0
         Y          3.0  16.000000  1.000000  15.0  15.50  16.0  16.50  17.0
DE       N        132.0  22.583333  4.758346   7.0  20.00  22.0  26.00  45.0
         Y        313.0  23.801917  4.955481  11.0  20.00  24.0  27.00  38.0
DL       N          0.0        NaN       NaN   NaN    NaN   NaN    NaN   NaN
         Y          2.0  25.500000  0.707107  25.0  25.25  25.5  25.75  26.0
DT       N        144.0  26.340278  5.487638  17.0  22.75  26.0  30.00  51.0
         Y        272.0  27.294118  5.657008   8.0  24.00  27.0  31.00  49.0
FB       N         52.0  21.230769  5.429099   7.0  17.75  21.5  24.00  35.0
         Y         68.0  22.720588  5.009977  14.0  19.00  23.0  25.00  37.0
FS       N         77.0  15.350649  3.995939   5.0  14.00  15.0  17.00  24.0
         Y        159.0  16.150943  4.009780   7.0  14.00  16.0  19.00  28.0
ILB      N         82.0  21.853659  5.244920   8.0  18.00  21.0  26.00  36.0
         Y        171.0  22.596491  4.325817  11.0  19.00  22.0  25.00  35.0
K        N          1.0  14.000000       NaN  14.0  14.00  14.0  14.00  14.0
         Y          0.0        NaN       NaN   NaN    NaN   NaN    NaN   NaN
LB       N          3.0  16.333333  4.725816  11.0  14.50  18.0  19.00  20.0
         Y          8.0  19.625000  3.502550  15.0  16.75  20.0  21.50  25.0
LS       N          2.0  21.000000  4.242641  18.0  19.50  21.0  22.50  24.0
         Y          1.0  30.000000       NaN  30.0  30.00  30.0  30.00  30.0
NT       N          0.0        NaN       NaN   NaN    NaN   NaN    NaN   NaN
OG       N        139.0  24.028777  4.944537  12.0  21.00  23.0  28.00  40.0
         Y        221.0  26.226244  5.370241  15.0  23.00  26.0  29.00  45.0
OL       N          2.0  22.500000  0.707107  22.0  22.25  22.5  22.75  23.0
         Y          2.0  30.000000  5.656854  26.0  28.00  30.0  32.00  34.0
OLB      N        111.0  20.441441  4.124615  12.0  17.50  20.0  23.50  31.0
         Y        275.0  22.767273  4.840939  10.0  20.00  23.0  26.00  41.0
OT       N        117.0  23.179487  4.971670  14.0  20.00  23.0  26.00  36.0
         Y        293.0  24.744027  5.063231   9.0  21.00  24.0  28.00  40.0
P        N          3.0  15.666667  6.429101  11.0  12.00  13.0  18.00  23.0
         Y          1.0  23.000000       NaN  23.0  23.00  23.0  23.00  23.0
QB       N         11.0  17.909091  3.562430  14.0  15.50  18.0  19.50  26.0
         Y          8.0  21.375000  2.924649  16.0  19.75  22.0  23.25  25.0
RB       N        211.0  18.327014  4.207949   3.0  15.00  18.0  21.00  29.0
         Y        270.0  19.622222  4.704450   5.0  17.00  19.0  23.00  32.0
SS       N         76.0  16.736842  4.315456   6.0  13.75  17.0  20.00  28.0
         Y        124.0  17.750000  4.637467   7.0  15.00  17.0  21.00  31.0
TE       N        117.0  19.102564  4.194382   7.0  17.00  19.0  21.00  35.0
         Y        195.0  21.123077  4.287987  12.0  18.00  21.0  24.00  35.0
WR       N        138.0  14.152174  4.416132   6.0  11.00  14.0  17.00  35.0
         Y        228.0  15.276316  4.649661   4.0  12.00  15.0  18.00  38.0

In [5]:
df.groupby(["position", "drafted"])["shuttle"].describe()

                  count      mean       std   min     25%    50%     75%   max
position drafted
C        N         65.0  4.666769  0.194929  3.89  4.5800  4.650  4.7700  4.99
         Y         88.0  4.606023  0.170034  4.14  4.5075  4.610  4.6950  5.04
CB       N        123.0  4.195203  0.148121  3.86  4.0900  4.200  4.2800  4.56
         Y        330.0  4.139576  0.154644  3.75  4.0400  4.140  4.2400  4.76
DB       N          1.0  4.220000       NaN  4.22  4.2200  4.220  4.2200  4.22
         Y          3.0  4.183333  0.140119  4.07  4.1050  4.140  4.2400  4.34
DE       N        110.0  4.459364  0.175981  4.03  4.3500  4.445  4.5675  4.88
         Y        301.0  4.412093  0.183399  3.90  4.3000  4.400  4.5100  5.10
DL       N          1.0  4.400000       NaN  4.40  4.4000  4.400  4.4000  4.40
         Y          1.0  4.000000       NaN  4.00  4.0000  4.000  4.0000  4.00
DT       N        129.0  4.652713  0.198489  4.13  4.5300  4.660  4.7800  5.27
         Y        240.0  4.614500  0.190704  4.10  4.4900  4.620  4.7325  5.14
FB       N         43.0  4.404186  0.163812  4.09  4.2950  4.380  4.5200  4.73
         Y         65.0  4.325231  0.186087  3.91  4.2100  4.320  4.4300  4.85
FS       N         67.0  4.228955  0.155214  3.86  4.1300  4.210  4.3200  4.72
         Y        137.0  4.176277  0.142746  3.80  4.0900  4.190  4.2800  4.47
ILB      N         71.0  4.327887  0.139498  4.00  4.2400  4.330  4.4050  4.75
         Y        139.0  4.284892  0.149071  3.88  4.2000  4.290  4.3800  4.64
K        N          0.0       NaN       NaN   NaN     NaN    NaN     NaN   NaN
         Y          0.0       NaN       NaN   NaN     NaN    NaN     NaN   NaN
LB       N          3.0  4.363333  0.145717  4.21  4.2950  4.380  4.4400  4.50
         Y          4.0  4.440000  0.231084  4.29  4.2975  4.345  4.4875  4.78
LS       N          2.0  4.305000  0.035355  4.28  4.2925  4.305  4.3175  4.33
         Y          0.0       NaN       NaN   NaN     NaN    NaN     NaN   NaN
NT       N          1.0  4.930000       NaN  4.93  4.9300  4.930  4.9300  4.93
OG       N        141.0  4.836950  0.236356  4.13  4.6900  4.820  4.9400  5.68
         Y        202.0  4.712426  0.197044  4.13  4.5800  4.710  4.8400  5.22
OL       N          1.0  4.750000       NaN  4.75  4.7500  4.750  4.7500  4.75
         Y          1.0  4.730000       NaN  4.73  4.7300  4.730  4.7300  4.73
OLB      N        104.0  4.339519  0.181960  3.98  4.2175  4.315  4.4325  4.94
         Y        240.0  4.263708  0.144813  3.83  4.1675  4.280  4.3700  4.63
OT       N        112.0  4.806786  0.196126  4.40  4.6875  4.805  4.9225  5.25
         Y        280.0  4.732000  0.198697  4.33  4.5900  4.715  4.8700  5.40
P        N          2.0  4.500000  0.042426  4.47  4.4850  4.500  4.5150  4.53
         Y          1.0  4.410000       NaN  4.41  4.4100  4.410  4.4100  4.41
QB       N        147.0  4.366395  0.174120  3.99  4.2550  4.370  4.4750  4.87
         Y        176.0  4.295227  0.163091  3.87  4.1700  4.290  4.4100  4.78
RB       N        168.0  4.271607  0.147292  3.86  4.1700  4.250  4.3800  4.73
         Y        221.0  4.236878  0.157612  3.82  4.1200  4.220  4.3400  4.67
SS       N         67.0  4.237463  0.174315  3.86  4.1350  4.230  4.3250  4.68
         Y         89.0  4.165843  0.134069  3.87  4.0900  4.170  4.2500  4.54
TE       N        102.0  4.419118  0.134275  4.10  4.3300  4.430  4.5000  4.75
         Y        183.0  4.323333  0.161161  3.98  4.1950  4.320  4.4300  4.82
WR       N        234.0  4.232650  0.152905  3.86  4.1225  4.220  4.3300  4.63
         Y        374.0  4.192914  0.149930  3.73  4.0900  4.185  4.2875  5.01

In [6]:
df.groupby(["position", "drafted"])["vert_leap_in"].describe()

                  count       mean       std   min     25%    50%     75%  \
position drafted
C        N         66.0  27.386364  2.895348  21.0  25.500  27.00  29.000
         Y         89.0  28.556180  2.889478  23.0  26.500  28.50  30.500
CB       N        162.0  35.191358  2.853099  29.0  33.000  35.00  37.000
         Y        389.0  36.097686  2.759140  28.5  34.000  36.00  38.000
DB       N          1.0  34.500000       NaN  34.5  34.500  34.50  34.500
         Y          3.0  35.666667  2.466441  34.0  34.250  34.50  36.500
DE       N        125.0  31.864000  3.154858  24.5  29.500  32.00  34.000
         Y        334.0  33.211078  2.954545  25.0  31.500  33.00  35.000
DL       N          1.0  30.500000       NaN  30.5  30.500  30.50  30.500
         Y          3.0  31.833333  2.516611  29.5  30.500  31.50  33.000
DT       N        137.0  28.948905  3.137349  20.5  27.000  29.00  31.000
         Y        275.0  29.336364  2.901759  20.5  27.500  29.50  31.000
FB       N         52.0  32.500000  3.101233  25.5  30.000  32.00  34.125
         Y         73.0  32.726027  3.016207  26.5  31.000  32.50  35.000
FS       N         84.0  34.684524  2.811101  28.0  33.000  34.75  36.625
         Y        163.0  36.046012  3.074090  29.5  34.250  36.00  37.750
ILB      N         85.0  32.364706  2.975483  25.5  30.000  32.50  34.000
         Y        163.0  33.601227  2.792273  24.5  32.000  33.50  35.500
K        N          0.0        NaN       NaN   NaN     NaN    NaN     NaN
         Y          1.0  33.500000       NaN  33.5  33.500  33.50  33.500
LB       N          3.0  31.666667  1.258306  30.5  31.000  31.50  32.250
         Y         10.0  34.150000  2.625198  30.5  31.875  34.25  36.625
LS       N          3.0  28.166667  2.362908  25.5  27.250  29.00  29.500
         Y          2.0  30.500000  3.535534  28.0  29.250  30.50  31.750
NT       N          0.0        NaN       NaN   NaN     NaN    NaN     NaN
OG       N        149.0  26.722819  3.139593  17.5  24.500  26.50  29.000
         Y        213.0  27.971831  2.773128  21.5  26.000  28.00  30.000
OL       N          2.0  24.250000  1.060660  23.5  23.875  24.25  24.625
         Y          1.0  26.500000       NaN  26.5  26.500  26.50  26.500
OLB      N        114.0  33.302632  3.357476  25.0  31.500  33.00  35.000
         Y        279.0  34.915771  3.183970  24.5  32.500  34.50  37.000
OT       N        121.0  26.880165  3.130512  19.5  25.000  27.00  29.000
         Y        296.0  28.310811  3.069757  19.5  26.500  28.50  30.500
P        N          4.0  30.625000  3.198307  27.0  28.500  30.75  32.875
         Y          2.0  30.500000  0.000000  30.5  30.500  30.50  30.500
QB       N        153.0  30.627451  3.024315  23.0  29.000  30.50  32.500
         Y        186.0  31.384409  3.277495  21.5  29.000  31.25  33.500
RB       N        221.0  33.890045  2.706993  25.5  32.000  34.00  35.500
         Y        297.0  34.939394  3.104274  27.0  33.000  35.00  37.000
SS       N         74.0  34.641892  2.701497  28.0  33.000  35.00  36.500
         Y        120.0  36.041667  2.752068  30.5  34.000  36.00  38.000
TE       N        114.0  31.654386  3.364235  25.0  29.000  31.50  34.000
         Y        201.0  33.310945  3.126752  24.5  31.000  33.00  35.000
WR       N        269.0  34.198885  3.045433  25.0  32.500  34.00  36.000
         Y        465.0  35.673118  3.002626  26.0  33.500  35.50  37.500

                   max
position drafted
C        N        37.5
         Y        34.5
CB       N        45.0
         Y        45.0
DB       N        34.5
         Y        38.5
DE       N        40.5
         Y        42.0
DL       N        30.5
         Y        34.5
DT       N        36.0
         Y        38.5
FB       N        41.0
         Y        40.0
FS       N        41.5
         Y        46.0
ILB      N        39.5
         Y        40.5
K        N         NaN
         Y        33.5
LB       N        33.0
         Y        37.5
LS       N        30.0
         Y        33.0
NT       N         NaN
OG       N        35.5
         Y        36.0
OL       N        25.0
         Y        26.5
OLB      N        45.5
         Y        42.5
OT       N        36.0
         Y        35.5
P        N        34.0
         Y        30.5
QB       N        40.0
         Y        39.0
RB       N        43.5
         Y        43.5
SS       N        41.0
         Y        41.5
TE       N        39.0
         Y        43.5
WR       N        43.5
         Y        45.0

In [7]:
df.groupby(["position", "drafted"])["broad_jump_in"].describe()
#LB 110 - 116 N Y 116 - 138

                  count        mean       std    min     25%    50%     75%  \
position drafted
C        N         65.0  100.015385  6.771937   85.0   96.00  101.0  104.00
         Y         86.0  101.825581  5.970894   91.0   97.00  101.0  105.00
CB       N        159.0  118.786164  4.708415  108.0  116.00  119.0  122.00
         Y        391.0  121.621483  5.582477  105.0  117.50  122.0  125.00
DB       N          1.0  120.000000       NaN  120.0  120.00  120.0  120.00
         Y          3.0  123.666667  7.637626  117.0  119.50  122.0  127.00
DE       N        121.0  112.214876  5.749212  100.0  108.00  112.0  116.00
         Y        329.0  114.620061  6.293024   99.0  111.00  114.0  119.00
DL       N          1.0  115.000000       NaN  115.0  115.00  115.0  115.00
         Y          3.0  124.000000  6.928203  116.0  122.00  128.0  128.00
DT       N        132.0  104.204545  6.100605   86.0  100.00  105.0  108.00
         Y        263.0  105.019011  5.996470   83.0  102.00  105.0  109.00
FB       N         51.0  112.254902  6.134633  100.0  109.00  111.0  115.50
         Y         73.0  112.520548  5.333619  102.0  109.00  113.0  116.00
FS       N         81.0  118.395062  5.112922  107.0  115.00  119.0  122.00
         Y        161.0  120.701863  6.189552  102.0  116.00  121.0  125.00
ILB      N         86.0  112.081395  4.594665   98.0  109.25  112.0  115.00
         Y        161.0  115.173913  5.105836  104.0  111.00  115.0  119.00
K        N          1.0  111.000000       NaN  111.0  111.00  111.0  111.00
         Y          1.0  116.000000       NaN  116.0  116.00  116.0  116.00
LB       N          3.0  114.000000  3.464102  110.0  113.00  116.0  116.00
         Y         10.0  122.800000  4.237400  116.0  120.25  122.5  126.50
LS       N          3.0  105.333333  6.027714   99.0  102.50  106.0  108.50
         Y          1.0  115.000000       NaN  115.0  115.00  115.0  115.00
NT       N          0.0         NaN       NaN    NaN     NaN    NaN     NaN
OG       N        137.0   98.036496  6.747994   82.0   93.00   98.0  103.00
         Y        205.0  101.463415  6.416498   85.0   97.00  101.0  106.00
OL       N          1.0   97.000000       NaN   97.0   97.00   97.0   97.00
         Y          1.0  106.000000       NaN  106.0  106.00  106.0  106.00
OLB      N        119.0  114.781513  5.025629  104.0  112.00  115.0  117.00
         Y        285.0  117.877193  6.206171  100.0  114.00  118.0  122.00
OT       N        114.0   99.017544  7.096032   73.0   94.00   99.5  104.00
         Y        285.0  102.294737  6.445121   82.0   98.00  102.0  106.00
P        N          2.0  114.500000  6.363961  110.0  112.25  114.5  116.75
         Y          1.0  114.000000       NaN  114.0  114.00  114.0  114.00
QB       N        154.0  108.461039  6.399687   91.0  104.00  109.0  113.00
         Y        186.0  110.274194  6.666989   96.0  106.00  110.0  114.00
RB       N        218.0  116.119266  5.464970  104.0  112.00  116.0  120.00
         Y        285.0  118.821053  5.867634  102.0  115.00  119.0  122.00
SS       N         75.0  117.240000  4.964305  106.0  114.00  117.0  121.00
         Y        123.0  120.308943  5.776053  107.0  116.00  120.0  124.00
TE       N        113.0  111.504425  6.227995   94.0  108.00  111.0  115.00
         Y        196.0  115.163265  6.123840   92.0  111.00  115.0  119.00
WR       N        263.0  117.878327  5.595154   99.0  114.00  118.0  122.00
         Y        441.0  120.589569  5.850158  105.0  117.00  120.0  124.00

                    max
position drafted
C        N        117.0
         Y        127.0
CB       N        133.0
         Y        147.0
DB       N        120.0
         Y        132.0
DE       N        124.0
         Y        133.0
DL       N        115.0
         Y        128.0
DT       N        119.0
         Y        130.0
FB       N        134.0
         Y        128.0
FS       N        134.0
         Y        141.0
ILB      N        123.0
         Y        127.0
K        N        111.0
         Y        116.0
LB       N        116.0
         Y        128.0
LS       N        111.0
         Y        115.0
NT       N          NaN
OG       N        111.0
         Y        119.0
OL       N         97.0
         Y        106.0
OLB      N        131.0
         Y        139.0
OT       N        115.0
         Y        126.0
P        N        119.0
         Y        114.0
QB       N        126.0
         Y        128.0
RB       N        134.0
         Y        137.0
SS       N        128.0
         Y        134.0
TE       N        127.0
         Y        134.0
WR       N        133.0
         Y        139.0

In [8]:
df.groupby(["position", "drafted"])["3cone"].describe()

                  count      mean       std   min     25%    50%     75%   max
position drafted
C        N         64.0  7.877344  0.313284  7.28  7.6275  7.895  8.1000  8.63
         Y         87.0  7.703793  0.253709  7.22  7.5100  7.640  7.8650  8.34
CB       N        119.0  7.065126  0.263728  6.34  6.8950  7.040  7.2350  7.96
         Y        315.0  6.954825  0.230385  6.44  6.7950  6.940  7.0900  7.85
DB       N          0.0       NaN       NaN   NaN     NaN    NaN     NaN   NaN
         Y          3.0  6.786667  0.127410  6.64  6.7450  6.850  6.8600  6.87
DE       N        110.0  7.434364  0.311674  6.80  7.2125  7.460  7.6025  8.59
         Y        297.0  7.369731  0.305478  6.78  7.1700  7.320  7.5300  8.80
DL       N          1.0  7.380000       NaN  7.38  7.3800  7.380  7.3800  7.38
         Y          3.0  7.096667  0.141539  7.01  7.0150  7.020  7.1400  7.26
DT       N        124.0  7.805968  0.362758  7.10  7.5275  7.760  8.0625  9.02
         Y        238.0  7.748908  0.333690  6.85  7.5300  7.730  7.9400  9.16
FB       N         43.0  7.404186  0.279278  6.85  7.2000  7.400  7.5650  8.10
         Y         65.0  7.304000  0.321436  6.72  7.1000  7.270  7.5300  8.38
FS       N         65.0  7.149385  0.233839  6.56  6.9800  7.100  7.2800  7.82
         Y        134.0  7.028358  0.225162  6.48  6.8625  7.040  7.1800  7.62
ILB      N         68.0  7.336618  0.279785  6.70  7.1500  7.345  7.5100  8.07
         Y        136.0  7.227059  0.267158  6.56  7.0475  7.210  7.3800  7.91
K        N          0.0       NaN       NaN   NaN     NaN    NaN     NaN   NaN
         Y          0.0       NaN       NaN   NaN     NaN    NaN     NaN   NaN
LB       N          1.0  7.180000       NaN  7.18  7.1800  7.180  7.1800  7.18
         Y          6.0  6.920000  0.149933  6.75  6.8125  6.900  7.0025  7.15
LS       N          1.0  7.260000       NaN  7.26  7.2600  7.260  7.2600  7.26
         Y          0.0       NaN       NaN   NaN     NaN    NaN     NaN   NaN
NT       N          0.0       NaN       NaN   NaN     NaN    NaN     NaN   NaN
OG       N        134.0  8.085597  0.365915  7.21  7.8700  8.065  8.3075  9.61
         Y        194.0  7.866186  0.311616  7.26  7.6300  7.845  8.0700  9.00
OL       N          0.0       NaN       NaN   NaN     NaN    NaN     NaN   NaN
         Y          1.0  7.550000       NaN  7.55  7.5500  7.550  7.5500  7.55
OLB      N        102.0  7.305196  0.301868  6.67  7.1200  7.250  7.4675  8.32
         Y        236.0  7.151102  0.250627  6.64  6.9775  7.115  7.2900  7.84
OT       N        106.0  8.060283  0.354222  7.31  7.8300  8.040  8.2775  9.04
         Y        275.0  7.869855  0.337778  7.06  7.6350  7.860  8.0400  9.28
P        N          0.0       NaN       NaN   NaN     NaN    NaN     NaN   NaN
         Y          1.0  7.280000       NaN  7.28  7.2800  7.280  7.2800  7.28
QB       N        143.0  7.260070  0.316387  6.55  7.0350  7.270  7.4450  8.25
         Y        173.0  7.164971  0.268291  6.66  6.9600  7.120  7.3400  7.97
RB       N        165.0  7.173152  0.239068  6.63  7.0000  7.150  7.3300  8.18
         Y        213.0  7.072864  0.253578  6.50  6.8900  7.050  7.1800  7.97
SS       N         64.0  7.086562  0.276292  6.47  6.8975  7.050  7.2800  7.78
         Y         91.0  7.024615  0.230735  6.51  6.8800  7.020  7.1700  7.55
TE       N         98.0  7.357653  0.294691  6.83  7.1500  7.330  7.5000  8.36
         Y        179.0  7.196089  0.269470  6.71  6.9900  7.140  7.3750  8.30
WR       N        227.0  7.078722  0.282778  6.42  6.8900  7.070  7.2700  7.94
         Y        358.0  6.973687  0.229763  6.50  6.8100  6.960  7.0900  8.07

In [70]:
df.groupby(["position", "drafted"])["name"].describe()

                 count unique                 top freq
position drafted
C        N          79     79       steve justice    1
         Y         104    104       john sullivan    1
CB       N         179    178       chris hawkins    2
         Y         442    440        kevin thomas    2
DB       N           1      1          art maulet    1
         Y           3      3    shaquill griffin    1
DE       N         149    149         ugo chinasa    1
         Y         375    375     demarcus walker    1
DL       N           1      1          ken ekanem    1
         Y           3      3     ifeadi odenigbo    1
DT       N         157    157        cory grissom    1
         Y         324    323         chris jones    2
FB       N          55     55     jehuu caulcrick    1
         Y          79     79         joey iosefa    1
FS       N          96     96      quentin harris    1
         Y         182    182      dashon goldson    1
ILB      N          99     99          ink aleaga    1
         Y         193    193          jon bostic    1
K        N           6      6       justin manton    1
         Y           4      4         blair walsh    1
LB       N           3      3      riley bullough    1
         Y          12     12         marquel lee    1
LS       N           4      4        tanner carew    1
         Y           2      2         colin holba    1
NT       N           1      1          josh tupou    1
OG       N         172    172        brian newnam    1
         Y         250    250       sean locklear    1
OL       N           2      2     javarius leamon    1
         Y           2      2  jermaine eluemunor    1
OLB      N         136    136      john lotulelei    1
         Y         324    324       prince shembo    1
OT       N         142    142      bobby williams    1
         Y         341    341      willie beavers    1
P        N          12     12       trevor daniel    1
         Y           4      4         bryan anger    1
QB       N         161    161     steve sarkisian    1
         Y         216    215          alex smith    2
RB       N         250    250    carnell williams    1
         Y         328    327     adrian peterson    2
SS       N          91     91      eddie pleasant    1
         Y         146    146    sabby piscitelli    1
TE       N         138    138      darrell strong    1
         Y         226    225          alex smith    2
WR       N         292    292       aaron fairooz    1
         Y         514    511       mike williams    3

In [90]:
df = df.drop_duplicates()

In [91]:
len(df)

6298