In [59]:
import numpy as np
import pandas as pd

In [60]:
combine = pd.read_csv("testcombine2019.csv")
prospects = pd.read_csv("prospectinfo.csv")
prospects

                 player          college position height  weight
0            Bosa, Nick         Ohio St.     EDGE    6-4     266
1     Williams, Quinnen          Alabama       DL    6-3     303
2           Allen, Josh         Kentucky     EDGE    6-5     262
3            Oliver, Ed          Houston       DL    6-2     287
4          White, Devin              LSU       LB    6-0     237
5         Sweat, Montez      Miss. State     EDGE    6-6     260
6        Taylor, Jawaan          Florida       OL    6-5     312
7       Williams, Jonah          Alabama       OL    6-4     302
8          Gary, Rashan         Michigan       DL    6-4     277
9    Wilkins, Christian          Clemson       DL    6-3     315
10      Ferrell, Clelin          Clemson     EDGE    6-4     264
11     Williams, Greedy              LSU       CB    6-2     185
12      Haskins, Dwayne         Ohio St.       QB    6-3     231
13        Murray, Kyler         Oklahoma       QB   5-10     207
14        Metcalf, D.K.         Ole Miss       WR    6-3     228
15        Murphy, Byron       Washington       CB   5-11     190
16      Hockenson, T.J.             Iowa       TE    6-5     251
17         Burns, Brian      Florida St.     EDGE    6-5     249
18       Dillard, Andre   Washington St.       OL    6-5     315
19          Bush, Devin         Michigan       LB   5-11     234
20       Baker, Deandre          Georgia       CB   5-11     193
21         Jacobs, Josh          Alabama       RB   5-10     220
22     Lawrence, Dexter          Clemson       DL    6-4     342
23           Ford, Cody         Oklahoma       OL    6-4     329
24     Simmons, Jeffery      Miss. State       DL    6-4     301
25           Lock, Drew         Missouri       QB    6-4     228
26      Brown, Marquise         Oklahoma       WR    5-9     166
27           Fant, Noah             Iowa       TE    6-4     249
28       Polite, Jachai          Florida     EDGE    6-3     258
29      Adderley, Nasir         Delaware        S    6-0     206
..                  ...              ...      ...    ...     ...
510      Wilkins, Kevin          Rutgers       DL    6-2     306
511      Mangum, Tanner              BYU       QB    6-3     205
512       Meier, Carson         Oklahoma       TE    6-5     250
513        Dungey, Eric         Syracuse       QB    6-4     228
514    Ware, Aca'Cedric              USC       RB    6-0     205
515      Harris, Deonte       Assumption       WR    5-6     173
516         Mayes, Brad           Lehigh       QB    6-2     220
517      Jones, Charles           Tulane       TE    6-4     255
518      Coutts, Steven       California        P    6-4     220
519     Saunders, Mavin      Florida St.       TE    6-5     256
520        Dillon, Kano           Oregon       TE    6-5     256
521         Harris, Tim         Virginia       CB    6-2     205
522       Guyton, Jalen      North Texas       WR    6-1     208
523   Snelson, Dredrick              UCF       WR    6-0     206
524       Gilbert, Mark             Duke       CB    6-1     175
525      Render, Keegan             Iowa       OL    6-4     307
526  Zaccheaus, Olamide         Virginia       WR    5-8     193
527        Davis, Titus              UCF     EDGE    6-3     250
528      Evans, Datryan          Friends       TE    6-5     239
529   Holloman, Joshuwa      E. Michigan       RB   5-10     200
530  Simpson, Cortrelle         Richmond       WR   5-11     185
531     Sumpter, Justin   Kennesaw State       WR    6-1     221
532    Bingham, Ronheen     Arkansas St.     EDGE    6-2     242
533         Brock, Trey        Hillsdale       WR    6-2     214
534  Washington, Jerome          Rutgers       TE    6-4     243
535       Roberts, Greg           Baylor       DL    6-5     264
536    Allegretti, Nick         Illinois       OL    6-4     310
537    Searight, Isaiah          Fordham       TE    6-4     245
538       Vahe, Patrick            Texas       OL    6-2     321
539       Calhoun, Shaq  Mississippi St.        G    6-2     310

[540 rows x 5 columns]

In [61]:
playerdata = combine.merge(prospects, how="left", on="player")

In [71]:
playerdata.head()

,player,bench,vert,broad,cone,twenty,forty,college,position,height,weight,ps,pps
0,"Abram, Johnathan",NaN,NaN,116.0,NaN,NaN,4.45,Miss. State,S,5-11,215,242,58.4209
1,"Adams, Paul",16.0,27.0,103.0,7.68,4.74,5.18,Missouri,OL,6-6,317,4,50.0000
2,"Al-Shaair, Azeez",16.0,NaN,NaN,NaN,NaN,NaN,FAU,LB,6-1,234,15,80.0000
3,"Alaka, Otaro",20.0,36.0,131.0,NaN,NaN,4.82,Texas A&M,LB,6-3,239,15,80.0000
4,"Allen, Zach",23.0,31.5,116.0,6.88,4.04,5.00,Boston College,DL,6-4,281,4,75.0000

In [68]:
#playerdata["position"] = playerdata["position"].replace("EDGE","DE")
#position = pd.read_csv("positionscores.csv")
#playerdata.merge(position, how="left", on="position")
#playerdata
#playerdata = pd.read_csv("testingcombine2019.csv")
playerdata["position"] = playerdata["position"].replace("EDGE","DE")
position = pd.read_csv("positionscores.csv")
playerdata = playerdata.merge(position, how="left", on="position")

In [72]:
playerdata.head()

,player,bench,vert,broad,cone,twenty,forty,college,position,height,weight,ps,pps
0,"Abram, Johnathan",NaN,NaN,116.0,NaN,NaN,4.45,Miss. State,S,5-11,215,242,58.4209
1,"Adams, Paul",16.0,27.0,103.0,7.68,4.74,5.18,Missouri,OL,6-6,317,4,50.0000
2,"Al-Shaair, Azeez",16.0,NaN,NaN,NaN,NaN,NaN,FAU,LB,6-1,234,15,80.0000
3,"Alaka, Otaro",20.0,36.0,131.0,NaN,NaN,4.82,Texas A&M,LB,6-3,239,15,80.0000
4,"Allen, Zach",23.0,31.5,116.0,6.88,4.04,5.00,Boston College,DL,6-4,281,4,75.0000

In [100]:
colleges = pd.read_csv("collegescores.csv")
playerdata["college"] = playerdata["college"].replace({"BYU":"Brigham Young","TCU":"Texas Christian"})
playerdata = playerdata.merge(colleges, how="left", on="college")

In [110]:
#playerdata = playerdata.drop(["college","position"],1)
#playerdata.to_csv("testingcombine2019.csv", index=False)
playerdata = playerdata.rename(columns={"broad":"broad_jump_in","cone":"3cone","twenty":"shuttle","forty":"40yards",'height':"height_in","weight":"weight_lbs"})
playerdata

,player,benchpress,vert_jump_in,broad_jump_in,3cone,shuttle,40yards,height_in,weight_lbs,ps,pps,cs,pcs
0,"Abram, Johnathan",NaN,NaN,116.0,NaN,NaN,4.45,5-11,215,242,58.420900,57.0,61.403509
1,"Adams, Paul",16.0,27.0,103.0,7.68,4.74,5.18,6-6,317,4,50.000000,49.0,57.142857
2,"Al-Shaair, Azeez",16.0,NaN,NaN,NaN,NaN,NaN,6-1,234,15,80.000000,9.0,44.444444
3,"Alaka, Otaro",20.0,36.0,131.0,NaN,NaN,4.82,6-3,239,15,80.000000,80.0,60.000000
4,"Allen, Zach",23.0,31.5,116.0,6.88,4.04,5.00,6-4,281,4,75.000000,56.0,57.142857
5,"Allen, Josh",24.0,32.0,112.0,7.34,4.36,4.63,6-5,262,477,66.876310,37.0,56.756757
6,"Allen, Dakota",28.0,NaN,118.0,7.15,4.23,4.77,6-1,232,15,80.000000,40.0,50.000000
7,"Allen-Williams, Bryson",14.0,NaN,NaN,7.40,NaN,4.88,6-1,236,15,80.000000,73.0,64.383562
8,"Allison, Jeff",12.0,31.0,115.0,7.20,4.45,4.82,5-11,228,15,80.000000,37.0,62.162162
9,"Amadi, Ugo",18.0,32.5,115.0,7.21,4.19,4.51,5-9,199,242,58.420900,82.0,57.317073
10,"Anderson, Rodney",25.0,NaN,NaN,NaN,NaN,NaN,6-0,224,519,55.298651,100.0,68.000000
11,"Armstead, Ryquell",22.0,30.0,114.0,7.02,4.29,4.45,5-11,220,519,55.298651,19.0,78.947368
12,"Austin, Blessuan",15.0,NaN,NaN,NaN,NaN,NaN,6-1,198,592,66.891892,30.0,66.666667
13,"Bailey, Jake",24.0,28.0,103.0,NaN,NaN,4.72,6-1,200,20,20.000000,79.0,65.822785
14,"Bailey, Zack",NaN,33.0,117.0,NaN,NaN,NaN,6-5,299,4,50.000000,73.0,64.383562
15,"Baity, Derrick",10.0,38.5,127.0,7.06,4.31,NaN,6-2,197,592,66.891892,37.0,56.756757
16,"Baker, Deandre",14.0,NaN,118.0,NaN,NaN,4.52,5-11,193,592,66.891892,110.0,75.454545
17,"Ballentine, Corey",15.0,39.5,135.0,6.82,4.14,4.47,6-0,204,592,66.891892,1.0,0.000000
18,"Banogu, Ben",23.0,40.0,134.0,7.02,4.27,4.62,6-3,250,477,66.876310,55.0,60.000000
19,"Barnes, Alex",34.0,38.5,126.0,6.95,4.10,4.59,6-0,226,519,55.298651,53.0,62.264151
20,"Barton, Jackson",30.0,32.5,116.0,6.90,4.03,5.18,6-7,310,4,50.000000,63.0,60.317460
21,"Barton, Cody",25.0,27.0,109.0,7.85,4.66,4.64,6-2,237,15,80.000000,63.0,60.317460
22,"Bates, Ryan",28.0,27.0,102.0,7.45,4.53,5.09,6-4,306,4,50.000000,79.0,65.822785
23,"Battle, John",NaN,29.5,120.0,7.09,4.33,4.67,6-0,201,242,58.420900,120.0,70.000000
24,"Beckner, Terry",28.0,24.5,98.0,7.97,4.82,5.19,6-4,296,4,75.000000,49.0,57.142857
25,"Bell, Mike",10.0,30.0,118.0,7.10,4.46,4.83,6-3,210,242,58.420900,37.0,62.162162
26,"Benzschawel, Beau",20.0,NaN,NaN,NaN,NaN,5.24,6-6,309,4,50.000000,82.0,69.512195
27,"Blair, Marquise",NaN,35.0,125.0,NaN,NaN,4.48,6-1,195,242,58.420900,63.0,60.317460
28,"Blanton, Kendall",22.0,31.0,113.0,7.37,4.42,4.95,6-6,262,333,60.660661,49.0,57.142857
29,"Bosa, Nick",29.0,33.5,116.0,7.10,4.14,4.79,6-4,266,477,66.876310,106.0,71.698113
...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,"Watts, Armon",NaN,NaN,NaN,NaN,NaN,5.23,6-5,300,4,75.000000,79.0,60.759494
280,"Way, Jamarius",16.0,32.5,119.0,NaN,4.66,4.63,6-3,215,757,60.766182,3.0,33.333333
281,"Weber, Mike",22.0,33.5,NaN,NaN,NaN,4.47,5-10,211,519,55.298651,106.0,71.698113
282,"Webster, Ken",18.0,43.0,133.0,6.85,4.14,4.43,5-11,203,592,66.891892,56.0,60.714286
283,"Wesco, Trevon",24.0,31.0,117.0,7.18,4.38,4.89,6-3,267,333,60.660661,56.0,57.142857
284,"Wesley, Antoine",6.0,37.0,117.0,7.07,4.26,NaN,6-4,206,757,60.766182,40.0,50.000000
285,"Wesley, Alex",13.0,38.5,125.0,7.40,4.44,4.45,6-0,190,757,60.766182,2.0,100.000000
286,"West, Darius",19.0,33.5,113.0,NaN,NaN,4.39,5-11,208,242,58.420900,37.0,56.756757
287,"White, Devin",22.0,39.5,118.0,7.07,4.17,4.42,6-0,237,15,80.000000,120.0,70.000000
288,"Wilkins, Christian",28.0,29.5,107.0,NaN,4.55,5.04,6-3,315,4,75.000000,91.0,71.428571
289,"Williams, Dexter",17.0,36.0,130.0,7.00,4.16,4.57,5-11,212,519,55.298651,97.0,68.041237
290,"Williams, Trayveon",19.0,33.0,121.0,7.44,4.44,4.51,5-8,206,519,55.298651,80.0,60.000000
291,"Williams, James",NaN,36.5,118.0,7.01,4.25,4.58,5-9,197,519,55.298651,37.0,62.162162
292,"Williams, Jonah",23.0,28.0,100.0,8.01,4.79,5.12,6-4,302,4,50.000000,122.0,68.852459
293,"Williams, Quinnen",NaN,30.5,112.0,NaN,NaN,4.83,6-3,303,4,75.000000,122.0,68.852459
294,"Williams, Greedy",NaN,NaN,NaN,NaN,NaN,4.37,6-2,185,592,66.891892,120.0,70.000000
295,"Williams, Joejuan",17.0,NaN,NaN,NaN,NaN,4.64,6-4,211,592,66.891892,31.0,67.741935
296,"Willis, Khari",22.0,34.5,118.0,NaN,NaN,4.52,5-11,213,242,58.420900,75.0,54.666667
297,"Wilson, Caleb",NaN,29.0,113.0,7.20,4.40,4.56,6-4,240,333,60.660661,69.0,63.768116
298,"Wilson, Mack",NaN,32.0,117.0,NaN,NaN,NaN,6-1,240,15,80.000000,122.0,68.852459
299,"Wilson, Donovan",18.0,36.0,127.0,NaN,NaN,NaN,6-0,199,242,58.420900,80.0,60.000000
300,"Wingard, Andrew",9.0,36.5,121.0,7.08,4.20,4.56,6-0,209,242,58.420900,17.0,52.941176
301,"Winovich, Chase",18.0,30.5,116.0,6.94,4.11,4.59,6-3,256,477,66.876310,79.0,74.683544
302,"Wise, Daniel",22.0,27.5,112.0,7.53,4.37,5.28,6-3,281,4,75.000000,30.0,53.333333
303,"Wishnowsky, Mitch",NaN,32.5,117.0,NaN,NaN,4.63,6-2,218,20,20.000000,63.0,60.317460
304,"Woods, Zedrick",19.0,34.5,122.0,7.00,4.15,4.29,5-11,205,242,58.420900,56.0,60.714286
305,"Worthington, Evan",17.0,33.5,121.0,7.07,4.37,4.63,6-2,212,242,58.420900,51.0,60.784314
306,"Wren, Renell",30.0,32.0,118.0,7.65,4.53,5.01,6-5,318,4,75.000000,64.0,60.937500
307,"Ximines, Oshane",24.0,34.0,118.0,7.13,4.57,4.78,6-3,253,477,66.876310,3.0,0.000000
308,"Ya-Sin, Rock",18.0,39.5,120.0,7.31,4.31,4.51,6-0,192,592,66.891892,19.0,78.947368

In [121]:
for index, row in playerdata.iterrows():
    height = row["height_in"].split("-")
    height = int(height[0]) * 12 + int(height[1])
    playerdata.loc[index, "height_in"] = height

In [124]:
playerdata.to_csv("testingcombine2019.csv", index=False)