In [1]:
from splinter import Browser
import bs4 as BeautifulSoup
import pandas as pd
import time
import numpy as np

In [45]:
executable_path = {'executable_path':"chromedriver-windows.exe"}
page_link = "http://www.nfl.com/combine/tracker#day=fullresults"
browser = Browser('chrome',**executable_path, headless=False)
browser.driver.set_window_size(1360, 650)
browser.visit(page_link)

In [46]:
prospectives = []

In [47]:
nxtbutton = True
while(nxtbutton):
    rows = browser.find_by_css("div.tracker-table tbody tr")
    
    for row in rows:
        prospectives.append(row.find_by_css("td:nth-child(1)").text)

    if (len(browser.find_by_css("li.next a")) > 0):
        browser.find_by_css("li.next a").click()
    else:
        nxtbutton = False
        
prospect_df = pd.DataFrame({"player":prospectives})

In [48]:
for event in ["bench","vert","broad","cone","twenty","forty"]:
    listing = []
    
    browser.reload()
    time.sleep(2)
    browser.find_by_css("a."+event).click()
    
    nxtbutton = True
    while(nxtbutton):
        rows = browser.find_by_css("div.tracker-table tbody tr")
        time.sleep(3)

        for roww in browser.find_by_css("div.tracker-table tbody tr"):
            listing.append(roww.find_by_css("td:nth-child(4)").text)

        if (len(browser.find_by_css("li.next a")) > 0):
            browser.find_by_css("li.next a").click()
        else:
            nxtbutton = False
            prospect_df[event] = listing

In [52]:
prospect_df.head()

             player bench  vert  broad  cone twenty forty
0  Abram, Johnathan     -     -  116.0     -      -  4.45
1       Adams, Paul    16  27.0  103.0  7.68   4.74  5.18
2   Adderley, Nasir     -     -      -     -      -     -
3  Al-Shaair, Azeez    16     -      -     -      -     -
4      Alaka, Otaro    20  36.0  131.0     -      -  4.82

In [53]:
prospect_df = prospect_df.replace("-",np.nan)
prospect_df

                     player bench  vert  broad  cone twenty forty
0          Abram, Johnathan   NaN   NaN  116.0   NaN    NaN  4.45
1               Adams, Paul    16  27.0  103.0  7.68   4.74  5.18
2           Adderley, Nasir   NaN   NaN    NaN   NaN    NaN   NaN
3          Al-Shaair, Azeez    16   NaN    NaN   NaN    NaN   NaN
4              Alaka, Otaro    20  36.0  131.0   NaN    NaN  4.82
5               Allen, Zach    23  31.5  116.0  6.88   4.04  5.00
6               Allen, Josh    24  32.0  112.0  7.34   4.36  4.63
7             Allen, Dakota    28   NaN  118.0  7.15   4.23  4.77
8    Allen-Williams, Bryson    14   NaN    NaN  7.40    NaN  4.88
9             Allison, Jeff    12  31.0  115.0  7.20   4.45  4.82
10               Amadi, Ugo    18  32.5  115.0  7.21   4.19  4.51
11         Anderson, Rodney    25   NaN    NaN   NaN    NaN   NaN
12   Arcega-Whiteside, J.J.   NaN   NaN    NaN   NaN    NaN   NaN
13        Armstead, Ryquell    22  30.0  114.0  7.02   4.29  4.45
14         Austin, Blessuan    15   NaN    NaN   NaN    NaN   NaN
15             Bailey, Jake    24  28.0  103.0   NaN    NaN  4.72
16             Bailey, Zack   NaN  33.0  117.0   NaN    NaN   NaN
17           Baity, Derrick    10  38.5  127.0  7.06   4.31   NaN
18           Baker, Deandre    14   NaN  118.0   NaN    NaN  4.52
19        Ballentine, Corey    15  39.5  135.0  6.82   4.14  4.47
20              Banogu, Ben    23  40.0  134.0  7.02   4.27  4.62
21             Barnes, Alex    34  38.5  126.0  6.95   4.10  4.59
22               Bars, Alex   NaN   NaN    NaN   NaN    NaN   NaN
23          Barton, Jackson    30  32.5  116.0  6.90   4.03  5.18
24             Barton, Cody    25  27.0  109.0  7.85   4.66  4.64
25              Bates, Ryan    28  27.0  102.0  7.45   4.53  5.09
26             Battle, John   NaN  29.5  120.0  7.09   4.33  4.67
27           Beckner, Terry    28  24.5   98.0  7.97   4.82  5.19
28               Bell, Mike    10  30.0  118.0  7.10   4.46  4.83
29        Benzschawel, Beau    20   NaN    NaN   NaN    NaN  5.24
..                      ...   ...   ...    ...   ...    ...   ...
306           Way, Jamarius    16  32.5  119.0   NaN   4.66  4.63
307             Weber, Mike    22  33.5    NaN   NaN    NaN  4.47
308            Webster, Ken    18  43.0  133.0  6.85   4.14  4.43
309           Wesco, Trevon    24  31.0  117.0  7.18   4.38  4.89
310         Wesley, Antoine     6  37.0  117.0  7.07   4.26   NaN
311            Wesley, Alex    13  38.5  125.0  7.40   4.44  4.45
312            West, Darius    19  33.5  113.0   NaN    NaN  4.39
313            White, Devin    22  39.5  118.0  7.07   4.17  4.42
314      Wilkins, Christian    28  29.5  107.0   NaN   4.55  5.04
315        Williams, Dexter    17  36.0  130.0  7.00   4.16  4.57
316      Williams, Trayveon    19  33.0  121.0  7.44   4.44  4.51
317         Williams, James   NaN  36.5  118.0  7.01   4.25  4.58
318         Williams, Jonah    23  28.0  100.0  8.01   4.79  5.12
319       Williams, Quinnen   NaN  30.5  112.0   NaN    NaN  4.83
320        Williams, Greedy   NaN   NaN    NaN   NaN    NaN  4.37
321       Williams, Joejuan    17   NaN    NaN   NaN    NaN  4.64
322           Willis, Khari    22  34.5  118.0   NaN    NaN  4.52
323          Willis, Gerald   NaN   NaN    NaN   NaN    NaN   NaN
324           Wilson, Caleb   NaN  29.0  113.0  7.20   4.40  4.56
325            Wilson, Mack   NaN  32.0  117.0   NaN    NaN   NaN
326         Wilson, Donovan    18  36.0  127.0   NaN    NaN   NaN
327         Wingard, Andrew     9  36.5  121.0  7.08   4.20  4.56
328         Winovich, Chase    18  30.5  116.0  6.94   4.11  4.59
329            Wise, Daniel    22  27.5  112.0  7.53   4.37  5.28
330       Wishnowsky, Mitch   NaN  32.5  117.0   NaN    NaN  4.63
331          Woods, Zedrick    19  34.5  122.0  7.00   4.15  4.29
332       Worthington, Evan    17  33.5  121.0  7.07   4.37  4.63
333            Wren, Renell    30  32.0  118.0  7.65   4.53  5.01
334         Ximines, Oshane    24  34.0  118.0  7.13   4.57  4.78
335            Ya-Sin, Rock    18  39.5  120.0  7.31   4.31  4.51

[336 rows x 7 columns]

In [54]:
prospect_df = prospect_df.apply(pd.to_numeric, errors="ignore")
prospect_df

                     player  bench  vert  broad  cone  twenty  forty
0          Abram, Johnathan    NaN   NaN  116.0   NaN     NaN   4.45
1               Adams, Paul   16.0  27.0  103.0  7.68    4.74   5.18
2           Adderley, Nasir    NaN   NaN    NaN   NaN     NaN    NaN
3          Al-Shaair, Azeez   16.0   NaN    NaN   NaN     NaN    NaN
4              Alaka, Otaro   20.0  36.0  131.0   NaN     NaN   4.82
5               Allen, Zach   23.0  31.5  116.0  6.88    4.04   5.00
6               Allen, Josh   24.0  32.0  112.0  7.34    4.36   4.63
7             Allen, Dakota   28.0   NaN  118.0  7.15    4.23   4.77
8    Allen-Williams, Bryson   14.0   NaN    NaN  7.40     NaN   4.88
9             Allison, Jeff   12.0  31.0  115.0  7.20    4.45   4.82
10               Amadi, Ugo   18.0  32.5  115.0  7.21    4.19   4.51
11         Anderson, Rodney   25.0   NaN    NaN   NaN     NaN    NaN
12   Arcega-Whiteside, J.J.    NaN   NaN    NaN   NaN     NaN    NaN
13        Armstead, Ryquell   22.0  30.0  114.0  7.02    4.29   4.45
14         Austin, Blessuan   15.0   NaN    NaN   NaN     NaN    NaN
15             Bailey, Jake   24.0  28.0  103.0   NaN     NaN   4.72
16             Bailey, Zack    NaN  33.0  117.0   NaN     NaN    NaN
17           Baity, Derrick   10.0  38.5  127.0  7.06    4.31    NaN
18           Baker, Deandre   14.0   NaN  118.0   NaN     NaN   4.52
19        Ballentine, Corey   15.0  39.5  135.0  6.82    4.14   4.47
20              Banogu, Ben   23.0  40.0  134.0  7.02    4.27   4.62
21             Barnes, Alex   34.0  38.5  126.0  6.95    4.10   4.59
22               Bars, Alex    NaN   NaN    NaN   NaN     NaN    NaN
23          Barton, Jackson   30.0  32.5  116.0  6.90    4.03   5.18
24             Barton, Cody   25.0  27.0  109.0  7.85    4.66   4.64
25              Bates, Ryan   28.0  27.0  102.0  7.45    4.53   5.09
26             Battle, John    NaN  29.5  120.0  7.09    4.33   4.67
27           Beckner, Terry   28.0  24.5   98.0  7.97    4.82   5.19
28               Bell, Mike   10.0  30.0  118.0  7.10    4.46   4.83
29        Benzschawel, Beau   20.0   NaN    NaN   NaN     NaN   5.24
..                      ...    ...   ...    ...   ...     ...    ...
306           Way, Jamarius   16.0  32.5  119.0   NaN    4.66   4.63
307             Weber, Mike   22.0  33.5    NaN   NaN     NaN   4.47
308            Webster, Ken   18.0  43.0  133.0  6.85    4.14   4.43
309           Wesco, Trevon   24.0  31.0  117.0  7.18    4.38   4.89
310         Wesley, Antoine    6.0  37.0  117.0  7.07    4.26    NaN
311            Wesley, Alex   13.0  38.5  125.0  7.40    4.44   4.45
312            West, Darius   19.0  33.5  113.0   NaN     NaN   4.39
313            White, Devin   22.0  39.5  118.0  7.07    4.17   4.42
314      Wilkins, Christian   28.0  29.5  107.0   NaN    4.55   5.04
315        Williams, Dexter   17.0  36.0  130.0  7.00    4.16   4.57
316      Williams, Trayveon   19.0  33.0  121.0  7.44    4.44   4.51
317         Williams, James    NaN  36.5  118.0  7.01    4.25   4.58
318         Williams, Jonah   23.0  28.0  100.0  8.01    4.79   5.12
319       Williams, Quinnen    NaN  30.5  112.0   NaN     NaN   4.83
320        Williams, Greedy    NaN   NaN    NaN   NaN     NaN   4.37
321       Williams, Joejuan   17.0   NaN    NaN   NaN     NaN   4.64
322           Willis, Khari   22.0  34.5  118.0   NaN     NaN   4.52
323          Willis, Gerald    NaN   NaN    NaN   NaN     NaN    NaN
324           Wilson, Caleb    NaN  29.0  113.0  7.20    4.40   4.56
325            Wilson, Mack    NaN  32.0  117.0   NaN     NaN    NaN
326         Wilson, Donovan   18.0  36.0  127.0   NaN     NaN    NaN
327         Wingard, Andrew    9.0  36.5  121.0  7.08    4.20   4.56
328         Winovich, Chase   18.0  30.5  116.0  6.94    4.11   4.59
329            Wise, Daniel   22.0  27.5  112.0  7.53    4.37   5.28
330       Wishnowsky, Mitch    NaN  32.5  117.0   NaN     NaN   4.63
331          Woods, Zedrick   19.0  34.5  122.0  7.00    4.15   4.29
332       Worthington, Evan   17.0  33.5  121.0  7.07    4.37   4.63
333            Wren, Renell   30.0  32.0  118.0  7.65    4.53   5.01
334         Ximines, Oshane   24.0  34.0  118.0  7.13    4.57   4.78
335            Ya-Sin, Rock   18.0  39.5  120.0  7.31    4.31   4.51

[336 rows x 7 columns]

In [55]:
prospect_df.dtypes

player     object
bench     float64
vert      float64
broad     float64
cone      float64
twenty    float64
forty     float64
dtype: object

In [56]:
prospect_df.to_csv("testcombine2019.csv", index=False)

In [73]:
prospect_df[prospect_df["bench"].notnull() | prospect_df["vert"].notnull() | prospect_df["broad"].notnull() | prospect_df["cone"].notnull() | prospect_df["twenty"].notnull() | prospect_df["forty"].notnull()].to_csv("testcombine2019.csv", index=False)

In [2]:
executable_path = {'executable_path':"chromedriver-windows.exe"}
page_link = "https://www.cbssports.com/nfl/draft/prospect-rankings/"
browser = Browser('chrome',**executable_path, headless=False)
browser.driver.set_window_size(1360, 650)
browser.visit(page_link)

In [3]:
chroma = browser.find_by_xpath('//*[@id="video-playlist"]/section/div/div/div[3]/table/tbody/tr')

In [4]:
prospects = []
colleges = []
positions = []
heights = []
weights = []

In [5]:
for txt in chroma:
    try:
        if (txt.find_by_css("td:nth-child(2)").text.strip() != ""):
            name = txt.find_by_css("td:nth-child(2)").text
            name = name.split(" ")
            prospects.append(f"{name[1]}, {name[0]}")
    except:
        pass
    
    try:
        if (txt.find_by_css("td:nth-child(3)").text.strip() != ""):
            colleges.append(txt.find_by_css("td:nth-child(3)").text.strip())
    except:
        pass
    
    try:
        if (txt.find_by_css("td:nth-child(5)").text.strip() != ""):
            positions.append(txt.find_by_css("td:nth-child(5)").text.strip())
    except:
        pass
    
    try:
        if (txt.find_by_css("td:nth-child(7)").text.strip() != ""):
            heights.append(txt.find_by_css("td:nth-child(7)").text.strip())
    except:
        pass
    
    try:
        if (txt.find_by_css("td:nth-child(8)").text.strip() != ""):
            weights.append(txt.find_by_css("td:nth-child(8)").text.strip())
    except:
        pass

In [8]:
prospect_info = pd.DataFrame({"player":prospects,"college":colleges,"position":positions,"height":heights,'weight':weights})
prospect_info

                 player         college position height weight
0            Bosa, Nick        Ohio St.     EDGE    6-4    266
1     Williams, Quinnen         Alabama       DL    6-3    303
2           Allen, Josh        Kentucky     EDGE    6-5    262
3            Oliver, Ed         Houston       DL    6-2    287
4          White, Devin             LSU       LB    6-0    237
5         Sweat, Montez     Miss. State     EDGE    6-6    260
6        Taylor, Jawaan         Florida       OL    6-5    312
7       Williams, Jonah         Alabama       OL    6-4    302
8          Gary, Rashan        Michigan       DL    6-4    277
9    Wilkins, Christian         Clemson       DL    6-3    315
10      Ferrell, Clelin         Clemson     EDGE    6-4    264
11     Williams, Greedy             LSU       CB    6-2    185
12      Haskins, Dwayne        Ohio St.       QB    6-3    231
13        Murray, Kyler        Oklahoma       QB   5-10    207
14        Metcalf, D.K.        Ole Miss       WR    6-3    228
15        Murphy, Byron      Washington       CB   5-11    190
16      Hockenson, T.J.            Iowa       TE    6-5    251
17         Burns, Brian     Florida St.     EDGE    6-5    249
18       Dillard, Andre  Washington St.       OL    6-5    315
19          Bush, Devin        Michigan       LB   5-11    234
20       Baker, Deandre         Georgia       CB   5-11    193
21         Jacobs, Josh         Alabama       RB   5-10    220
22     Lawrence, Dexter         Clemson       DL    6-4    342
23           Ford, Cody        Oklahoma       OL    6-4    329
24     Simmons, Jeffery     Miss. State       DL    6-4    301
25           Lock, Drew        Missouri       QB    6-4    228
26      Brown, Marquise        Oklahoma       WR    5-9    166
27           Fant, Noah            Iowa       TE    6-4    249
28       Polite, Jachai         Florida     EDGE    6-3    258
29      Adderley, Nasir        Delaware        S    6-0    206
..                  ...             ...      ...    ...    ...
509        Crump, Koron     Arizona St.       LB    6-3    215
510      Wilkins, Kevin         Rutgers       DL    6-2    306
511      Mangum, Tanner             BYU       QB    6-3    205
512       Meier, Carson        Oklahoma       TE    6-5    250
513        Dungey, Eric        Syracuse       QB    6-4    228
514    Ware, Aca'Cedric             USC       RB    6-0    205
515      Harris, Deonte      Assumption       WR    5-6    173
516         Mayes, Brad          Lehigh       QB    6-2    220
517      Jones, Charles          Tulane       TE    6-4    255
518      Coutts, Steven      California        P    6-4    220
519     Saunders, Mavin     Florida St.       TE    6-5    256
520        Dillon, Kano          Oregon       TE    6-5    256
521         Harris, Tim        Virginia       CB    6-2    205
522       Guyton, Jalen     North Texas       WR    6-1    208
523   Snelson, Dredrick             UCF       WR    6-0    206
524       Gilbert, Mark            Duke       CB    6-1    175
525      Render, Keegan            Iowa       OL    6-4    307
526  Zaccheaus, Olamide        Virginia       WR    5-8    193
527        Davis, Titus             UCF     EDGE    6-3    250
528      Evans, Datryan         Friends       TE    6-5    239
529   Holloman, Joshuwa     E. Michigan       RB   5-10    200
530  Simpson, Cortrelle        Richmond       WR   5-11    185
531     Sumpter, Justin  Kennesaw State       WR    6-1    221
532    Bingham, Ronheen    Arkansas St.     EDGE    6-2    242
533         Brock, Trey       Hillsdale       WR    6-2    214
534  Washington, Jerome         Rutgers       TE    6-4    243
535       Roberts, Greg          Baylor       DL    6-5    264
536    Allegretti, Nick        Illinois       OL    6-4    310
537    Searight, Isaiah         Fordham       TE    6-4    245
538       Vahe, Patrick           Texas       OL    6-2    321

[539 rows x 5 columns]

In [9]:
prospect_info.to_csv("prospectinfo.csv", index=False)