In [14]:
from xgboost import XGBClassifier
from xgboost import plot_importance
from matplotlib import pyplot

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from numpy import sort
from sklearn.feature_selection import SelectFromModel

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from itertools import combinations

In [15]:
df = pd.read_csv("QB-Train.csv")
#df = df.drop(["year","name","college","position"],1)
df.head()
#377

,year,name,college,position,height_in,weight_lbs,40yards,benchpress,vert_leap_in,broad_jump_in,shuttle,3cone,drafted
0,2007,zac taylor,Nebraska,QB,74.38,216,5.08,NaN,30.5,110.0,4.60,7.39,N
1,2010,zac robinson,Oklahoma State,QB,74.50,214,4.68,NaN,35.0,110.0,4.40,7.24,Y
2,2013,zac dysert,Miami (OH),QB,75.00,227,4.81,NaN,NaN,NaN,NaN,NaN,Y
3,1997,wally richardson,Penn State,QB,76.40,221,4.95,NaN,31.0,109.0,4.47,7.97,Y
4,2006,vince young,Texas,QB,76.60,229,4.48,NaN,NaN,NaN,NaN,NaN,Y

In [16]:
df["hasstats"] = ""

In [17]:
from splinter import Browser
from sys import platform
import os
import csv
import re

executable_path = None

if platform == "linux" or platform == "linux2":
    executable_path = {'executable_path': os.path.join("binaries", "chromedriver-linux")}
elif platform == "darwin":
    executable_path = {'executable_path': os.path.join("binaries", "chromedriver-mac")}
elif platform == "win32":
    executable_path = {'executable_path': os.path.join("..","..","binaries", "chromedriver-windows.exe")}

browser = Browser('chrome', **executable_path, headless=False)

In [18]:
for index, row in df.iterrows():
    if (df.loc[index,"hasstats"] == ""):
        x = row["name"]
        browser.visit(f"https://www.sports-reference.com/cfb/search/search.fcgi?hint=&search={x}")
        if (len(browser.find_by_css("table#passing")) > 0):
            #elem = len(browser.find_by_css("td[data-stat='rec']"))
            #testit.loc[index, "Crec"] = browser.find_by_css("td[data-stat='rec']")[elem-1].text
            #testit.loc[index, "Cyds"] = browser.find_by_css("td[data-stat='rec_yds']")[elem-1].text
            #testit.loc[index, "CTD"] = browser.find_by_css("td[data-stat='rec_td']")[elem-1].text
            df.loc[index,"hasstats"] = 1
        elif (len(browser.find_by_css("div.search-item")) == 0):
            df.loc[index,"hasstats"] = 0
        else:
            listed = browser.find_by_css("div.search-item")
            
            print()
            
            for x in listed:
                if (re.sub(r'\(.*\)', "", row["college"]).strip() in x.find_by_css("div.search-item-league").text):
                    x.find_by_css("div.search-item-name a").click()
                    if (len(browser.find_by_css("table#passing")) > 0):
                        #elem = len(browser.find_by_css("td[data-stat='rec']"))
                        #testit.loc[index, "Crec"] = browser.find_by_css("td[data-stat='rec']")[elem-1].text
                        #testit.loc[index, "Cyds"] = browser.find_by_css("td[data-stat='rec_yds']")[elem-1].text
                        #testit.loc[index, "CTD"] = browser.find_by_css("td[data-stat='rec_td']")[elem-1].text
                        df.loc[index,"hasstats"] = 1
                        break
                    else:
                        df.loc[index,"hasstats"] = 0
                        break
                else:
                    df.loc[index,"hasstats"] = 0

AttributeError: 'ElementList' object has no attribute 'text'

In [8]:
df

,year,name,college,position,height_in,weight_lbs,40yards,benchpress,vert_leap_in,broad_jump_in,shuttle,3cone,drafted,hasstats
0,1997,jim arellanes,Frenso State (CA),QB,75.10,211,5.19,NaN,27.0,102.0,4.67,8.03,N,1
1,1997,mike cherry,Murray State (KY),QB,75.90,222,5.11,NaN,28.5,105.0,4.38,7.80,Y,1
2,1997,chuck clements,Houston,QB,74.60,211,4.98,NaN,31.5,108.0,4.36,7.69,Y,1
3,1997,marcus crandell,East Carolina (NC),QB,71.40,204,4.78,NaN,30.0,105.0,4.67,8.25,N,1
4,1997,jason davis,Western State Colorado,QB,75.50,220,4.92,NaN,30.5,107.0,4.33,7.85,N,0
5,1997,koy detmer,Colorado,QB,72.90,180,5.14,NaN,28.5,103.0,4.37,7.79,Y,1
6,1997,jim druckenmiller,Virginia Tech,QB,76.60,234,NaN,NaN,29.0,106.0,4.28,7.92,Y,1
7,1997,lance funderburk,Valdosta State (GA),QB,76.40,227,5.23,NaN,27.0,97.0,NaN,NaN,N,0
8,1997,jason martin,Louisiana Tech,QB,74.40,234,5.01,NaN,29.0,101.0,4.47,7.81,N,1
9,1997,brad otton,Southern California,QB,78.10,224,5.00,NaN,31.5,112.0,4.39,7.54,N,1
10,1997,jake plummer,Arizona State,QB,74.30,195,4.96,NaN,30.0,111.0,4.29,7.30,Y,1
11,1997,wally richardson,Penn State,QB,76.40,221,4.95,NaN,31.0,109.0,4.47,7.97,Y,1
12,1997,steve sarkisian,Brigham Young,QB,72.40,208,4.96,NaN,30.0,104.0,4.51,8.16,N,1
13,1997,danny wuerffel,Florida,QB,73.80,212,4.90,NaN,28.0,100.0,4.42,7.69,Y,1
14,1998,charlie batch,Eastern Michigan,QB,73.90,216,4.89,NaN,33.5,118.0,4.11,7.60,Y,1
15,1998,thad busby,Florida State,QB,74.10,223,4.97,NaN,30.5,110.0,NaN,NaN,N,1
16,1998,ryan clement,Miami (FL),QB,73.00,212,5.02,NaN,31.0,104.0,4.39,7.85,N,1
17,1998,john dutton,Nevada Las Vegas,QB,75.90,219,4.68,NaN,29.0,104.0,4.22,7.55,Y,0
18,1998,shane fortney,Northern Iowa,QB,73.60,225,4.72,NaN,33.5,114.0,4.30,7.74,N,1
19,1998,dan gonzalez,East Carolina (NC),QB,74.60,214,4.89,NaN,29.0,104.0,4.23,7.58,N,1
20,1998,paul kaiser,Central Missouri,QB,74.60,211,4.78,NaN,34.5,114.0,4.04,7.25,N,0
21,1998,chris mccoy,Navy,QB,69.80,196,4.80,15.0,29.5,109.0,NaN,NaN,N,1
22,1998,mike mcqueary,Penn State,QB,76.30,223,5.16,NaN,26.0,99.0,4.40,7.79,N,1
23,1998,ron powlus,Notre Dame,QB,73.60,219,5.10,NaN,26.0,98.0,4.35,7.53,N,1
24,1998,cory sauter,Minnesota,QB,76.10,218,4.98,NaN,31.0,109.0,4.15,7.45,N,1
25,1998,matt sherman,Iowa,QB,73.90,207,5.06,NaN,26.5,103.0,4.37,7.68,N,1
26,1999,todd bandhaur,Iowa State,QB,75.00,236,5.26,NaN,31.0,103.0,4.61,7.66,N,0
27,1999,michael bishop,Kansas State,QB,73.00,205,4.85,NaN,33.0,113.0,4.62,7.63,Y,1
28,1999,aaron brooks,Virginia,QB,75.50,203,4.59,NaN,35.5,118.0,4.29,7.52,Y,1
29,1999,mike cook,William & Mary (VA),QB,71.60,207,4.84,NaN,33.5,112.0,4.32,7.29,N,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,2017,jerod evans,Virginia Tech,QB,74.63,232,4.80,NaN,26.5,112.0,4.41,NaN,N,
348,2017,chad kelly,Mississippi,QB,74.00,224,NaN,NaN,NaN,NaN,4.08,NaN,Y,
349,2017,deshone kizer,Notre Dame,QB,76.13,233,4.83,NaN,30.5,107.0,4.53,7.40,Y,
350,2017,mitch leidner,Minnesota,QB,75.38,226,4.93,NaN,34.5,123.0,4.25,6.96,N,
351,2017,sefo liufau,Colorado,QB,75.38,232,5.08,NaN,27.0,105.0,4.45,7.32,N,
352,2017,patrick mahomes,Texas Tech,QB,74.13,225,4.80,NaN,30.0,114.0,4.08,6.88,Y,
353,2017,nathan peterman,Pittsburgh,QB,74.63,226,4.82,NaN,31.0,110.0,4.31,7.14,Y,
354,2017,cooper rush,Central Michigan,QB,74.63,228,4.93,NaN,27.0,105.0,4.47,7.23,N,
355,2017,alek torgersen,Pennsylvania,QB,75.00,230,NaN,NaN,NaN,NaN,4.31,NaN,N,
356,2017,mitchell trubisky,North Carolina,QB,74.13,222,4.67,NaN,27.5,116.0,4.25,6.87,N,
357,2017,deshaun watson,Clemson,QB,74.13,221,4.66,NaN,32.5,119.0,4.31,6.95,Y,
358,2017,davis webb,California,QB,77.00,229,4.79,NaN,33.0,118.0,NaN,6.92,Y,
359,2018,austin allen,Arkansas,QB,72.00,210,4.81,NaN,29.5,112.0,4.48,7.18,N,
360,2018,josh allen,Wyoming,QB,77.00,237,4.75,NaN,33.5,119.0,4.40,6.90,Y,
361,2018,jt barrett,Ohio State,QB,73.00,224,4.70,NaN,30.0,108.0,4.44,7.38,N,
362,2018,kurt benkert,Virginia,QB,75.00,218,4.95,16.0,31.0,112.0,4.33,7.15,N,
363,2018,sam darnold,Southern California,QB,75.00,221,4.85,NaN,26.5,105.0,4.40,6.96,Y,
364,2018,danny etling,Louisiana State,QB,74.00,222,4.76,NaN,30.5,114.0,4.37,7.09,Y,
365,2018,luke falk,Washington State,QB,76.00,215,NaN,NaN,26.5,103.0,NaN,NaN,Y,
366,2018,riley ferguson,Memphis,QB,75.00,212,4.98,NaN,29.0,110.0,4.40,6.96,N,
367,2018,quinton flowers,South Florida,QB,70.00,214,4.63,NaN,NaN,112.0,4.57,6.81,N,
368,2018,kyle lauletta,Richmond (VA),QB,75.00,222,4.81,NaN,31.0,113.0,4.07,6.95,Y,
369,2018,tanner lee,Nebraska,QB,76.00,218,4.98,NaN,32.0,115.0,4.41,7.00,Y,
370,2018,chase litton,Marshall (WV),QB,77.00,230,4.90,NaN,29.5,106.0,4.53,7.49,N,
371,2018,baker mayfield,Oklahoma,QB,73.00,215,4.84,NaN,29.0,111.0,4.28,7.00,Y,
372,2018,josh rosen,UCLA,QB,76.00,226,4.92,NaN,31.0,111.0,4.28,7.09,Y,
373,2018,mason rudolph,Oklahoma State,QB,77.00,235,4.90,NaN,26.0,NaN,NaN,NaN,Y,
374,2018,nic shimonek,Texas Tech,QB,75.00,220,4.88,NaN,28.5,101.0,4.32,7.28,N,
375,2018,mike white,Western Kentucky,QB,77.00,224,5.09,NaN,27.0,96.0,4.40,7.40,Y,
376,2018,logan woodside,Toledo,QB,73.00,213,4.79,NaN,31.5,103.0,4.15,6.94,Y,