In [1]:
from xgboost import XGBClassifier
from xgboost import plot_importance
from matplotlib import pyplot

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from numpy import sort
from sklearn.feature_selection import SelectFromModel

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from itertools import combinations

In [2]:
df = pd.read_csv("../OL-Train.csv")
df = df.drop(["year","name","college","position"],1)
df.head()
#377

,height_in,weight_lbs,40yards,benchpress,vert_leap_in,broad_jump_in,shuttle,3cone,drafted
0,76.1,344,5.60,NaN,24.5,92.0,5.25,8.85,N
1,76.4,296,5.22,21.0,32.5,111.0,4.13,NaN,Y
2,77.1,298,5.42,22.0,28.0,104.0,4.73,8.25,N
3,75.6,299,5.32,30.0,28.5,109.0,4.70,NaN,Y
4,73.6,307,5.19,22.0,28.0,102.0,4.61,NaN,Y

In [5]:
Y = df["drafted"]
Y = Y.replace("Y",1)
Y = Y.replace("N",0)

#X = df.drop(['weight_lbs', '3cone', 'Crec', 'Cyds', 'hasbling', 'hasawards', "drafted"], 1)
X = df.drop(["drafted"],1)
X

,height_in,weight_lbs,40yards,benchpress,vert_leap_in,broad_jump_in,shuttle,3cone
0,76.10,344,5.60,NaN,24.5,92.0,5.25,8.85
1,76.40,296,5.22,21.0,32.5,111.0,4.13,NaN
2,77.10,298,5.42,22.0,28.0,104.0,4.73,8.25
3,75.60,299,5.32,30.0,28.5,109.0,4.70,NaN
4,73.60,307,5.19,22.0,28.0,102.0,4.61,NaN
5,74.50,300,5.45,25.0,29.0,NaN,NaN,NaN
6,77.10,356,5.63,25.0,27.5,NaN,NaN,NaN
7,76.30,298,5.22,27.0,30.0,108.0,NaN,NaN
8,75.50,303,NaN,18.0,NaN,NaN,NaN,NaN
9,74.60,328,5.52,22.0,27.0,93.0,NaN,NaN
10,77.60,307,NaN,25.0,NaN,NaN,NaN,NaN
11,77.30,354,5.75,20.0,23.0,NaN,NaN,NaN
12,76.40,312,5.40,16.0,29.0,105.0,5.11,8.79
13,77.60,296,5.39,15.0,24.5,102.0,4.92,8.32
14,76.90,301,5.09,NaN,30.5,108.0,4.73,8.23
15,76.10,289,5.60,13.0,23.0,99.0,NaN,NaN
16,77.30,313,5.31,25.0,32.0,111.0,4.37,7.90
17,76.90,297,5.04,NaN,30.0,107.0,4.47,7.72
18,75.30,324,5.21,22.0,27.0,106.0,4.85,8.33
19,76.30,307,NaN,33.0,NaN,NaN,NaN,NaN
20,74.60,292,5.52,21.0,27.5,105.0,4.84,8.61
21,78.10,387,5.77,37.0,21.5,93.0,5.40,9.18
22,74.40,291,NaN,25.0,NaN,NaN,NaN,NaN
23,75.40,291,5.35,31.0,29.0,109.0,4.75,8.40
24,76.30,290,5.05,21.0,33.5,127.0,4.62,8.20
25,77.40,307,5.44,NaN,24.5,99.0,4.56,8.00
26,75.50,303,5.64,28.0,24.0,NaN,NaN,NaN
27,75.50,287,NaN,26.0,NaN,NaN,NaN,NaN
28,75.50,292,5.38,27.0,28.5,101.0,4.77,8.73
29,75.50,302,5.33,NaN,26.5,88.0,4.74,8.63
...,...,...,...,...,...,...,...,...
1062,77.00,315,5.41,23.0,27.0,105.0,4.55,7.97
1063,77.00,307,5.51,21.0,25.5,100.0,4.37,8.09
1064,79.25,321,5.61,18.0,26.0,103.0,5.17,8.35
1065,73.00,298,5.34,27.0,26.5,99.0,4.71,7.81
1066,80.00,345,5.85,14.0,19.5,82.0,5.38,7.87
1067,78.00,305,5.39,24.0,26.5,97.0,4.84,8.04
1068,77.00,298,5.33,19.0,NaN,NaN,NaN,NaN
1069,76.00,311,5.39,25.0,29.0,97.0,4.92,8.04
1070,76.00,307,5.23,23.0,23.5,104.0,4.78,7.77
1071,76.00,306,5.15,19.0,28.0,106.0,4.50,7.87
1072,77.00,309,5.23,17.0,30.0,105.0,4.77,7.89
1073,75.00,306,NaN,21.0,30.5,108.0,4.40,7.29
1074,76.00,319,5.58,17.0,23.5,98.0,4.95,7.86
1075,77.00,311,5.20,32.0,25.0,103.0,4.83,7.60
1076,76.00,320,5.45,18.0,24.0,96.0,4.80,7.84
1077,74.00,327,5.15,37.0,24.0,104.0,4.70,7.59
1078,77.00,305,5.32,28.0,27.0,101.0,4.86,7.92
1079,77.00,308,5.33,26.0,28.5,97.0,4.88,7.86
1080,76.00,303,5.34,15.0,29.5,103.0,NaN,NaN
1081,78.00,311,5.35,26.0,23.5,97.0,4.82,7.72
1082,77.00,325,NaN,35.0,26.5,105.0,4.62,7.65
1083,75.00,318,5.10,NaN,29.0,104.0,4.69,7.95
1084,76.00,310,5.09,25.0,33.5,111.0,4.69,7.50
1085,77.00,312,NaN,26.0,NaN,NaN,NaN,NaN
1086,76.00,308,NaN,24.0,NaN,NaN,NaN,NaN
1087,75.00,292,5.24,NaN,26.5,110.0,4.59,7.62
1088,78.00,315,5.22,35.0,33.5,113.0,4.77,NaN
1089,76.00,314,5.24,30.0,29.0,114.0,4.84,7.45
1090,77.00,310,5.40,NaN,28.0,109.0,4.90,7.70
1091,75.00,306,5.43,20.0,25.0,103.0,4.81,7.90

In [4]:
# split data into train and test sets
seed = 777
test_size = 0.30
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

# fit model on training data
model = XGBClassifier()
model.fit(X_train, y_train)

# make predictions for test data
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]

# evaluate predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 68.60%
0.6859756097560976